### ISSUE TITLE
Project fails to build

### ISSUE THREAD

**Issue by voroshil** [over64/greact#2]
Following error generated in Jenkins:

22:17:55 > Task :compileTestJava FAILED
22:17:55 /var/lib/jenkins/workspace/iias-greact/plugin/src/test/java/util/TestServer.java:8: error: appBasePackage has private access in RPC
22:17:55     public TestServer() {super(appBasePackage);}
22:17:55                                ^
22:17:55 Note: Some input files use preview language features.
22:17:55 Note: Recompile with -Xlint:preview for details.
22:17:55 1 error
22:17:55 
22:17:55 FAILURE: Build failed with an exception.
22:17:55 
22:17:55 * What went wrong:
22:17:55 Execution failed for task ':compileTestJava'.
22:17:55 > Compilation failed; see the compiler error output for details.22:17:55 > Task :compileTestJava FAILED
22:17:55 /var/lib/jenkins/workspace/iias-greact/plugin/src/test/java/util/TestServer.java:8: error: appBasePackage has private access in RPC
22:17:55     public TestServer() {super(appBasePackage);}
22:17:55                                ^
22:17:55 Note: Some input files use preview language features.
22:17:55 Note: Recompile with -Xlint:preview for details.
22:17:55 1 error
22:17:55 
22:17:55 FAILURE: Build failed with an exception.
22:17:55 
22:17:55 * What went wrong:
22:17:55 Execution failed for task ':compileTestJava'.
22:17:55 > Compilation failed; see the compiler error output for details.22:17:55 > Task :compileTestJava FAILED
22:17:55 /var/lib/jenkins/workspace/iias-greact/plugin/src/test/java/util/TestServer.java:8: error: appBasePackage has private access in RPC
22:17:55     public TestServer() {super(appBasePackage);}
22:17:55                                ^
22:17:55 Note: Some input files use preview language features.
22:17:55 Note: Recompile with -Xlint:preview for details.
22:17:55 1 error
22:17:55 
22:17:55 FAILURE: Build failed with an exception.
22:17:55 
22:17:55 * What went wrong:
22:17:55 Execution failed for task ':compileTestJava'.
22:17:55 > Compilation failed; see the compiler error output for details.

**Comment by over64** [comment]
nice
